Squashed 'llvm/tools/lldb/' changes from 049a7a0..52d3a34
52d3a34 Add Modulecache::GetAndPut method which wraps sequence of Get and Put (if module wasn't found in cache) calls.
717dcf0 Fix the ConvenienceVariablesCase tests after r234993
ce93990 Bug 23051 - Fix zombie processes after lldb-server tests
2fdb0e1 Add teardown hook to shutdown an inferior process
cc4df22 Skip TestMiVar test case to get build green
f88b1ca Fixed remote failures in TestCPP11EnumTypes, probably others
0eadeed Skip reverse connect test when running remotely
0c0392a TestConvenienceVariables - fixed a Linux problem
1db4e5a Exception registers aren't supported outside of Darwin
0d65af3 Add single stepping logic for linux arm
b152706 Fix breakpoint trap opcode detection for arm linux
86f0ffe Fix test makefile after r234949.
07227ef Change SymbolVendor::GetCompileUnitAtIndex() and SymbolVendor::Dump() to make sure they are thread safe.
21c458b MacOSX needs a space between $(ARCHFLAG) and $(ARCH) otherwise we try to call clang with "-archx86_64" which doesn't work.
14d50c5 Remove unneeded include.
55d206d Fix printf warnings about a size mismatch on MacOSX.
3ba337c Remove unused functions that were causing warnings.
fdbdb84 Added some documentation for ForEachMacro.
081e0e0 Added support to ClangUserExpression for importing all the macros from the modules the user has loaded. These macros are currently imported textually into the expression's source code, which turns out not to impose the horrific string processing overhead that I thought it would, but I still plan to look into performance improvements.
6f1f402 Updated IRForTarget to change the way we generate relocations.  We used to do GEP on a pointer to the result type, which is wrong.  We should be doing GEP on a pointer to char, which allows us to offset correctly.
d52c632 Fix handling of the executable arg which contains spaces (MI)
dab238f Simplify some lldb-mi tests by using the Base.addTearDownHook()
6aefe80 Fix XCode build after r234870.
33e52ad Additions to RenderScriptRuntime in prep for detection of RenderScript modules and moving of the command interpreter manipulation to after construction.
0141c21 Adds Register Context Linux/POSIX for ARM Architecture
7070067 Remove gcc xfail for TestTargetWatchAddress.
8f99841 Remove gcc xfail for TestWatchpointMultipleThreads.
4ce0a88 [TestPluginCommands] Add skipIfGcc at the right place.
6844a38 Skip the TestGdbRemoteRegisterState.test_grp_register_save_restore_works_no_suffix_debugserver_dsym test on OS X according to the bug 23181
457654c Skip libc++ data formmatting tests on Windows.  libc++ hasn't been ported to windows yet.
4b920a3 Be sure to complete base classes when importing them.
2ebf5a4 Missing `-lpthread` causes gcc test failure.
ae4415c Skip a few tests on OS X according to the bug 23181
3050b4c Fix CMICmnStreamStdout::WritePriv which causes a stack overflow (MI)
50c483a fixing msvc build (format string z is not supported)
b28a924 Making linking against Python simpler on Windows.
358a3f5 Allow the variable view to get synthetic values if they are available in "gui" mode.
5e7b782 Cleanup virtual methods and mark them as "override" and remove "virtual".
cb47651 [TestFormatters, TestDataFormatterSynthVal] Mark as xfail.
dedddb6 [TestAnonymous] Enable all tests for GCC
ebe1c38 Use llvm::sys::fs::create_directories to create new directory on Windows.
dbc588b Check in missing file.
894711c Add logging plugin for Windows
f23f1c9 Remove 'z' modifier from printf/sscanf operations in AdbClient  - the modifier isn't supported by MS C++ compiler.
19a74ee Wrap socket error handling with SetLastError and IsInterrupted internal functions which can properly treat Windows and POSIX errors.
e2aa561 Fix a problem where 'process launch' was not correctly re-quoting arguments for the inferior process when handing them down for the actual launch
1376b87 Skip lldb-server tests according to bug 23181
2e97a24 Don't hardcode the name of the plugin - or it will get out of date, and this code will be broken
e0bd730 The dyld shared cache class table is not present in the iOS simulator, so do not actually warn to people when running under the simulator
0e3bd65 Fix printf format specifier to silence warning.
082523a [ItaniumABILanguageRuntime] Remove an unneccesary 'typename' keyword.
27f8ed3 [RenderScriptRuntime] Fix build after r234522.
3c9431b [TestBitfields] Correct the attribute name to "aligned" in the testcase.
5b1d7a3 [IRForTarget] Strenghten handling of alternate mangling.
6d2a8bb Fix Debugger::HandleProcessEvent in case when ProcessIOHandler doesn't exist
546ac6d [Python] Fix issue configuring sys.path during startup.
2305047 Fix @skipUnlessPlatform and @skipIfPlatform decorators to work on classes.
9fa5857 Install a diagnostic consumer into each new AST context as the first thing we do.  This prevents crashes if some of the initial setup produces messages or errors.
89a57da Added the RenderScript language runtime plugin to the .xcodeproj.
07f162d Initial language runtime support for RenderScript.
377ecd4 Fix Xcode build after MipsLinuxSignals.cpp was added.
42b6f5d Fix expectedFailureLLGS to expect failure when host platform is not linux.
c511271 Add info on running remote test suite to the website
6e3fc84 Generate an event when a pending breakpoint binds
5e9a225 Fix MiGdbSetShowTestCase.test_lldbmi_gdb_set_ouptut_radix after r234476
4440c6d Refactor CMICmnLLDBDebuggerHandleEvents/CMICmnLLDBDebugSessionInfo/CMICmnLLDBDebugSessionInfoVarObj (MI)
a3dab55 [LLDB][MIPS] Add LinuxSignals for mips64 and change trap opcode for mips64el. Patch by Sagar Thakur
7cc4a1a Missed moving a variable during my previous revision 234455.
105c209 Darwin read()/pread()/fread() and write()/pwrite()/fwrite() calls can only write INT_MAX bytes at a time.
d01add3 Fix resolution of certain recursive types.
29cc386 Fix segfault when doing `thread info` on a thread without stop info.
892796b Fix -Wformat-pedantic warnings
412374c Remove redundant virtual for member functions marked 'override'.
7024cc9 Force the inclusion of the LLVMSupport lib. Otherwise, the build (might?) fails with an undefined reference to 'llvm::llvm_is_multithreaded()'
8733ed3 Add documentation about remote debugging to the website
2acde2e Fix compilation failure caused by r234366.
47236ba Make sure the OperatingSystem plug-ins will work on linux as well. This goes with my previous fix with revision 234364.
ed30f6d Fix stepping a virtual thread when the python operating system was enabled.
8974a43 Added a testcase that checks that struct arguments are passed to Objective-C methods correctly.
89312b0 Made the struct types test case a little stricter, by verifying that we can pass a struct-typed variable to a function that takes structs.
cc756a4 Fix bug where an additional O packet is sent after inferior exits.
6aa7898 Delete port forwarding if ConnectRemote fails.
b9d3a7e Fixed a problem where the second @import statement in a session would be silently ignored by the compiler because the compiler looked at its SourceLocation and decided it had already handled it.
6d7e919 Fix host config for Android and remove android specific part form Linux.
c6ac2d7 Remove check for windows when compiling scripts directory
c224df1 Don't compile scripts directory if LLDB_DISABLE_PYTHON is set
74bc91d Add some documentation about cross-compilation to www.
035c915 Ignore mapping symbols on aarch64
ff17694 implement gdb-set output-radix
471f01a Fixed a crash because we weren't generating type-safe relocations against @reloc_placeholder.
8846601 Fix check for options in "command alias"
be773c8 Enable a test in TestSTL for GCC.
d4fb41c Fix an issue where LLDB could crash when trying to figure out the return value layout for an invalid type
258ef7d If memory read does not find a NULL terminator, still print whatever it gathered instead of just NOP'ing out
b87ff2a Ignore IOError from missing child.log.
2ceba773 We have an issue where if you use a C function right now that has no prototype, it isn't marked as extern "C" and the name to lookup is some C++ mangled form of the name.
cdcbdc1 Fix printing of function names during unwind logging.
b29cd76 test: Move amd64 -> x86_64 translation to getArchitecture()
0aac6e1 test: Add amd64 architecture alias for x86_64
1fe2076 Copy paste error in gdb-remote doc.
46872c9 Use insert instead of append when adding to sys.path.
f6c4a15 [dotest.py] Present a better error when lldb module can't be found.
e7d4aea Fix FreeBSD crash after r233837

git-subtree-dir: llvm/tools/lldb
git-subtree-split: 52d3a348f9ec3ae3a7c7ccdaff4948674cba9bf8